export type JsonValue = string | number | boolean | null | JsonObject | JsonValue[];
export type JsonObject = { [key: string]: JsonValue };

export function createBasicAppTemplate(appName: string) {
  const appId = `app:${appName}`;

  const appManifest = {
    format: 'evolua-app',
    version: '0.0.1',
    appModelVersion: 'v[0,[0,1]]',
    appId,
    name: appName,
    title: 'Login Demo',
    description: 'Generated by evolua-create-app',
    entryDimension: 'visual',
    dimensions: {
      structure: './dimensions/structure.evolua.json',
      visual: './dimensions/visual.evolua.json',
      data: './dimensions/data.evolua.json',
      behavior: './dimensions/behavior.evolua.json',
      surface: './dimensions/surface.evolua.json',
    },
    derived: {
      spatial: './derived/spatial.3djson',
    },
    buildTargets: [
      {
        id: 'target:web',
        kind: 'nextjs',
        name: 'Next.js App Router',
      },
    ],
    environment: {
      node: '>=20',
    },
    meta: {
      generatedBy: 'evolua-create-app',
      template: 'basic-app',
    },
  } satisfies JsonObject;

  const structure = {
    format: 'evolua-dimension',
    version: '0.0.1',
    appId,
    dimension: 'structure',
    roots: ['structure:page:login'],
    nodes: {
      'structure:page:login': {
        id: 'structure:page:login',
        kind: 'page',
        name: 'LoginPage',
        children: ['structure:section:login-form'],
      },
      'structure:section:login-form': {
        id: 'structure:section:login-form',
        kind: 'section',
        name: 'LoginFormSection',
        children: [
          'structure:text:login-title',
          'structure:component:email-input',
          'structure:component:password-input',
          'structure:component:submit-button',
          'structure:text:forgot-password-link',
        ],
      },
      'structure:text:login-title': {
        id: 'structure:text:login-title',
        kind: 'text',
        name: 'LoginTitle',
        children: [],
      },
      'structure:component:email-input': {
        id: 'structure:component:email-input',
        kind: 'component',
        name: 'EmailInput',
        children: [],
      },
      'structure:component:password-input': {
        id: 'structure:component:password-input',
        kind: 'component',
        name: 'PasswordInput',
        children: [],
      },
      'structure:component:submit-button': {
        id: 'structure:component:submit-button',
        kind: 'component',
        name: 'SubmitButton',
        children: [],
      },
      'structure:text:forgot-password-link': {
        id: 'structure:text:forgot-password-link',
        kind: 'text',
        name: 'ForgotPasswordLink',
        children: [],
      },
      'structure:page:forgot-password': {
        id: 'structure:page:forgot-password',
        kind: 'page',
        name: 'ForgotPasswordPage',
        children: ['structure:section:forgot-password-form'],
      },
      'structure:section:forgot-password-form': {
        id: 'structure:section:forgot-password-form',
        kind: 'section',
        name: 'ForgotPasswordFormSection',
        children: [
          'structure:text:forgot-password-title',
          'structure:text:forgot-password-description',
          'structure:component:forgot-password-email-input',
          'structure:component:forgot-password-submit-button',
        ],
      },
      'structure:text:forgot-password-title': {
        id: 'structure:text:forgot-password-title',
        kind: 'text',
        name: 'ForgotPasswordTitle',
        children: [],
      },
      'structure:text:forgot-password-description': {
        id: 'structure:text:forgot-password-description',
        kind: 'text',
        name: 'ForgotPasswordDescription',
        children: [],
      },
      'structure:component:forgot-password-email-input': {
        id: 'structure:component:forgot-password-email-input',
        kind: 'component',
        name: 'ForgotPasswordEmailInput',
        children: [],
      },
      'structure:component:forgot-password-submit-button': {
        id: 'structure:component:forgot-password-submit-button',
        kind: 'component',
        name: 'ForgotPasswordSubmitButton',
        children: [],
      },
    },
    meta: {
      canonical: true,
    },
  } satisfies JsonObject;

  const visual = {
    format: 'evolua-dimension',
    version: '0.0.1',
    appId,
    dimension: 'visual',
    nodes: {
      'structure:page:login': {
        structureNodeId: 'structure:page:login',
        componentType: 'Page',
        layout: { variant: 'centered-auth' },
        meta: {
          title: 'Entrar',
          description: 'Acesse sua conta no app Evolu[a].',
        },
      },
      'structure:section:login-form': {
        structureNodeId: 'structure:section:login-form',
        componentType: 'AuthCard',
        styleTokens: ['max-w-md', 'gap-4'],
      },
      'structure:text:login-title': {
        structureNodeId: 'structure:text:login-title',
        componentType: 'Text',
        props: { content: 'Entrar' },
        styleTokens: ['text-3xl', 'font-bold'],
      },
      'structure:component:email-input': {
        structureNodeId: 'structure:component:email-input',
        componentType: 'TextField',
        props: { label: 'E-mail' },
      },
      'structure:component:password-input': {
        structureNodeId: 'structure:component:password-input',
        componentType: 'PasswordField',
        props: { label: 'Senha' },
      },
      'structure:component:submit-button': {
        structureNodeId: 'structure:component:submit-button',
        componentType: 'Button',
        props: { label: 'Entrar' },
        styleTokens: ['primary'],
      },
      'structure:text:forgot-password-link': {
        structureNodeId: 'structure:text:forgot-password-link',
        componentType: 'Link',
        props: { content: 'Esqueci senha' },
        styleTokens: ['text-blue-500', 'underline'],
      },
      'structure:page:forgot-password': {
        structureNodeId: 'structure:page:forgot-password',
        componentType: 'Page',
        layout: { variant: 'centered-auth' },
      },
      'structure:section:forgot-password-form': {
        structureNodeId: 'structure:section:forgot-password-form',
        componentType: 'AuthCard',
        styleTokens: ['max-w-md', 'gap-4'],
      },
      'structure:text:forgot-password-title': {
        structureNodeId: 'structure:text:forgot-password-title',
        componentType: 'Text',
        props: { content: 'Recuperar senha' },
        styleTokens: ['text-3xl', 'font-bold'],
      },
      'structure:text:forgot-password-description': {
        structureNodeId: 'structure:text:forgot-password-description',
        componentType: 'Text',
        props: { content: 'Insira seu e-mail para receber as instruções.' },
        styleTokens: ['text-sm', 'text-zinc-600'],
      },
      'structure:component:forgot-password-email-input': {
        structureNodeId: 'structure:component:forgot-password-email-input',
        componentType: 'TextField',
        props: { label: 'E-mail' },
      },
      'structure:component:forgot-password-submit-button': {
        structureNodeId: 'structure:component:forgot-password-submit-button',
        componentType: 'Button',
        props: { label: 'Enviar instruções' },
        styleTokens: ['primary'],
      },
    },
    meta: {
      projects: 'structure',
      canonical: true,
    },
  } satisfies JsonObject;

  const data = {
    format: 'evolua-dimension',
    version: '0.0.1',
    appId,
    dimension: 'data',
    nodes: {
      'data:state:auth:email': {
        id: 'data:state:auth:email',
        kind: 'state',
        name: 'AuthEmailState',
        source: { kind: 'local-state' },
      },
      'data:state:auth:password': {
        id: 'data:state:auth:password',
        kind: 'state',
        name: 'AuthPasswordState',
        source: { kind: 'local-state' },
      },
      'data:binding:forgot-password-link': {
        id: 'data:binding:forgot-password-link',
        kind: 'binding',
        name: 'ForgotPasswordBinding',
        bindingRefs: [],
      },
    },
    meta: {
      canonical: true,
    },
  } satisfies JsonObject;

  const behavior = {
    format: 'evolua-dimension',
    version: '0.0.1',
    appId,
    dimension: 'behavior',
    nodes: {
      'behavior:event:submit-login': {
        id: 'behavior:event:submit-login',
        kind: 'event',
        name: 'SubmitLoginEvent',
        trigger: {
          kind: 'event',
          name: 'onPress',
          sourceRef: { id: 'structure:component:submit-button', kind: 'component' },
        },
      },
      'behavior:event:forgot-password': {
        id: 'behavior:event:forgot-password',
        kind: 'event',
        name: 'ForgotPasswordEvent',
        trigger: {
          kind: 'event',
          name: 'onClick',
          sourceRef: { id: 'structure:text:forgot-password-link', kind: 'text' },
        },
      },
      'route:forgot-password': {
        id: 'route:forgot-password',
        kind: 'route',
        name: 'ForgotPasswordRoute',
        path: '/forgot-password',
        pageRef: { id: 'structure:page:forgot-password', kind: 'page' },
        transitions: [
          {
            eventName: 'onClick',
            to: '/forgot-password',
          },
        ],
      },
    },
    meta: {
      canonical: true,
    },
  } satisfies JsonObject;

  const surface = {
    format: 'evolua-dimension',
    version: '0.0.1',
    appId,
    dimension: 'surface',
    root: 'surface:root',
    nodes: {
      'surface:root': {
        id: 'surface:root',
        kind: 'root-layout',
        lang: 'pt-BR',
        title: 'Login Demo',
        description: 'Materialized from the Evolu[a] canonical app model',
        themeRef: 'surface:theme:default',
      },
      'surface:theme:default': {
        id: 'surface:theme:default',
        kind: 'theme',
        colors: {
          background: '#09090b',
          foreground: '#f4f4f5',
          card: '#ffffff',
          cardForeground: '#18181b',
          mutedForeground: '#71717a',
          primary: '#18181b',
          primaryForeground: '#ffffff',
          accent: '#2563eb',
        },
        typography: {
          fontFamily: 'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, \'Segoe UI\', sans-serif',
        },
      },
    },
    meta: {
      canonical: true,
    },
  } satisfies JsonObject;

  const packageJson = {
    name: appName,
    version: '0.0.1',
    private: true,
    scripts: {
      dev: 'evolua dev',
      build: 'evolua build',
    },
    dependencies: {
      evolua: 'workspace:*',
    },
    evolua: {
      target: 'nextjs',
      packageManager: 'npm',
    },
  } satisfies JsonObject;

  return { appManifest, packageJson, structure, visual, data, behavior, surface };
}
