export function createBasicAppTemplate(appName) {
    const appId = `app:${appName}`;
    const appManifest = {
        format: 'evolua-app',
        version: '0.0.1',
        appModelVersion: 'v[0,[0,1]]',
        appId,
        name: appName,
        description: 'Generated by evolua-create-app',
        entryDimension: 'visual',
        dimensions: {
            structure: './dimensions/structure.evolua.json',
            visual: './dimensions/visual.evolua.json',
            data: './dimensions/data.evolua.json',
            behavior: './dimensions/behavior.evolua.json',
        },
        derived: {
            spatial: './derived/spatial.3djson',
        },
        meta: {
            generatedBy: 'evolua-create-app',
            template: 'basic-app',
        },
    };
    const structure = {
        format: 'evolua-dimension',
        version: '0.0.1',
        appId,
        dimension: 'structure',
        roots: ['structure:page:login'],
        nodes: {
            'structure:page:login': {
                id: 'structure:page:login',
                kind: 'page',
                name: 'LoginPage',
                children: ['structure:section:login-form'],
            },
            'structure:section:login-form': {
                id: 'structure:section:login-form',
                kind: 'section',
                name: 'LoginFormSection',
                children: [
                    'structure:text:login-title',
                    'structure:component:email-input',
                    'structure:component:password-input',
                    'structure:component:submit-button',
                    'structure:text:forgot-password-link',
                ],
            },
            'structure:text:login-title': {
                id: 'structure:text:login-title',
                kind: 'text',
                name: 'LoginTitle',
                children: [],
            },
            'structure:component:email-input': {
                id: 'structure:component:email-input',
                kind: 'component',
                name: 'EmailInput',
                children: [],
            },
            'structure:component:password-input': {
                id: 'structure:component:password-input',
                kind: 'component',
                name: 'PasswordInput',
                children: [],
            },
            'structure:component:submit-button': {
                id: 'structure:component:submit-button',
                kind: 'component',
                name: 'SubmitButton',
                children: [],
            },
            'structure:text:forgot-password-link': {
                id: 'structure:text:forgot-password-link',
                kind: 'text',
                name: 'ForgotPasswordLink',
                children: [],
            },
        },
        meta: {
            canonical: true,
        },
    };
    const visual = {
        format: 'evolua-dimension',
        version: '0.0.1',
        appId,
        dimension: 'visual',
        nodes: {
            'structure:page:login': {
                structureNodeId: 'structure:page:login',
                componentType: 'Page',
                layout: { variant: 'centered-auth' },
            },
            'structure:section:login-form': {
                structureNodeId: 'structure:section:login-form',
                componentType: 'AuthCard',
                styleTokens: ['max-w-md', 'gap-4'],
            },
            'structure:text:login-title': {
                structureNodeId: 'structure:text:login-title',
                componentType: 'Text',
                props: { content: 'Entrar' },
                styleTokens: ['text-3xl', 'font-bold'],
            },
            'structure:component:email-input': {
                structureNodeId: 'structure:component:email-input',
                componentType: 'TextField',
                props: { label: 'E-mail' },
            },
            'structure:component:password-input': {
                structureNodeId: 'structure:component:password-input',
                componentType: 'PasswordField',
                props: { label: 'Senha' },
            },
            'structure:component:submit-button': {
                structureNodeId: 'structure:component:submit-button',
                componentType: 'Button',
                props: { label: 'Entrar' },
                styleTokens: ['primary'],
            },
            'structure:text:forgot-password-link': {
                structureNodeId: 'structure:text:forgot-password-link',
                componentType: 'Link',
                props: { content: 'Esqueci senha' },
                styleTokens: ['text-blue-500', 'underline'],
            },
        },
        meta: {
            projects: 'structure',
            canonical: true,
        },
    };
    const data = {
        format: 'evolua-dimension',
        version: '0.0.1',
        appId,
        dimension: 'data',
        nodes: {
            'data:state:auth:email': {
                id: 'data:state:auth:email',
                kind: 'state',
                name: 'AuthEmailState',
                source: { kind: 'local-state' },
            },
            'data:state:auth:password': {
                id: 'data:state:auth:password',
                kind: 'state',
                name: 'AuthPasswordState',
                source: { kind: 'local-state' },
            },
            'data:binding:forgot-password-link': {
                id: 'data:binding:forgot-password-link',
                kind: 'binding',
                name: 'ForgotPasswordBinding',
                bindingRefs: [],
            },
        },
        meta: {
            canonical: true,
        },
    };
    const behavior = {
        format: 'evolua-dimension',
        version: '0.0.1',
        appId,
        dimension: 'behavior',
        nodes: {
            'behavior:event:submit-login': {
                id: 'behavior:event:submit-login',
                kind: 'event',
                name: 'SubmitLoginEvent',
                trigger: {
                    kind: 'event',
                    name: 'onPress',
                    sourceRef: { id: 'structure:component:submit-button', kind: 'component' },
                },
            },
            'behavior:event:forgot-password': {
                id: 'behavior:event:forgot-password',
                kind: 'event',
                name: 'ForgotPasswordEvent',
                trigger: {
                    kind: 'event',
                    name: 'onClick',
                    sourceRef: { id: 'structure:text:forgot-password-link', kind: 'text' },
                },
            },
            'route:forgot-password': {
                id: 'route:forgot-password',
                kind: 'route',
                name: 'ForgotPasswordRoute',
                path: '/forgot-password',
                pageRef: { id: 'structure:page:login', kind: 'page' },
                transitions: [
                    {
                        eventName: 'onClick',
                        to: '/forgot-password',
                    },
                ],
            },
        },
        meta: {
            canonical: true,
        },
    };
    return { appManifest, structure, visual, data, behavior };
}
